import { GlobalStyle } from "@/general/utils/GlobalStyle";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Valyuta kursi",
  description: "Generated by create next app",
  creator: "dadondev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}
